project:
  type: book
  output-dir: docs

book:
  title: "Controle Estatístico de Qualidade"
  
  author:
  - name: "Breno Cauã Rodrigues da Silva"
    orcid: 0009-0005-9740-2069
    affiliations:
      - name: "Universidade Federal do Pará"
      - name: "Instituto de Ciências Exatas e Naturais"
      - name: "Falculdade de Estatística"

  page-footer: 
    left: "Copyright 2025, **SILVA, B.C.R**" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/
  
  date: "05/06/2025"

  downloads: [pdf, docx]
  page-navigation: true

  chapters:
    - index.qmd
    - UsualPlots.qmd
    - Exercises.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-sections: true
    df-print: paged
    theme:
      light: [blue,custom.scss]
      dark:  [cyborg,custom.scss]
    code-fold: true
    code-tools: true
    code-link: true
    toc-title: Índice
    toc-location: right
  pdf:
    documentclass: scrreprt
    fig-pos: "H"
    number-sections: true
    pdf-engine: xelatex
    indent: true
    header-includes: |
      \usepackage{indentfirst}
    fontsize: 12pt
    geometry: [left=3cm, top=3cm, right=2cm, bottom=2cm]
    echo: false
  docx:
    number-sections: true

execute:
  echo: true
  warning: false
  message: false
  engine: knitr  # Garante suporte a múltiplas linguagens
  kernels:
    python: python3
    r: ir
  keep-hidden: true
  freeze: auto

lang: pt-BR